import "./globals.css";

export const metadata = {
  title: {
    absolute: "",
    default: "Next.js", // default property is usefull when you want a fallback title for child route segments they don't explicitly specify a title
    template: "",
  },
  description: "Generated by Next.js",
};

// function m() {
//   return (
//     <marquee
//       style={{
//         background:
//           "linear-gradient(to left, violet, indigo, blue, green, yellow, orange, red)",
//       }}
//     >
//       When did I learn these many things? JS, React, TS, Tailwind and now Next;
//       what an adventure!
//     </marquee>
//   );
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col w-full">
        {/* <header className="w-full h-16 bg-[#95C6D8]">
          <p>Header</p>
        </header> */}
        {/* {m()} */}
        {children}
        {/* <footer className="fixed bottom-0 w-full h-32 bg-gray-400">
          <p>Footer</p>
        </footer> */}
      </body>
    </html>
  );
}
