import MainHeader from "@/components/main-header";
import "../globals.css";

export const metadata = {
  title: {
    absolute: "",
    default: "Next.js",
    template: "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="page">
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
